---

- block:
    # for legacy compatibility, because ftp.debian.org backports is not available anymore
    - name: Remove the non-working backports repository for Jessie release
      lineinfile:
        path: /etc/apt/sources.list.d/ftp_debian_org_debian.list
        state: absent
        regexp: '.*ftp.debian.org/debian jessie-backports.*'

    - name: Bypass jessie-backports InRelease expiration
      copy:
        content: 'Acquire::Check-Valid-Until "false";'
        dest: /etc/apt/apt.conf.d/99cycloid-sphinx-check-valid-until

    - name: Add archive backports repository for Jessie release
      apt_repository:
        repo: "deb http://archive.debian.org/debian jessie-backports main"
        state: present
  tags:
    - sphinx-apt
  when: ansible_os_family == "Debian" and ansible_distribution_release == "jessie"

- name: Install sphinx Debian package
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ ubuntu_pkg }}"
  when: ansible_os_family == "Debian"

- name: Install sphinx RedHat dependencies
  yum: name={{ item }} state=present
  with_items:
    - postgresql-libs
    - unixODBC
  when: ansible_os_family == "RedHat"

- name: Install sphinx RedHat package
  yum:
    name: "{{ rhel_pkg }}"
    state: present
  when: ansible_os_family == "RedHat"
